import { Transaction } from '../src/types';

export interface NotificationSettings {
  emailRecipient: string;
  autoSendOnVerification: boolean;
  includeReceiptPdfLink: boolean;
  includeTruthChainProof: boolean;
  notifyOnDispatches: boolean;
}

export interface EmailSummaryLog {
  id: string;
  transactionId: string;
  itemTitle: string;
  recipientEmail: string;
  subject: string;
  sentAt: string;
  status: 'DELIVERED' | 'FAILED';
  summaryHtml: string;
  amount: number;
  currency: string;
  truthChainProofHash: string;
}

let notificationSettings: NotificationSettings = {
  emailRecipient: 'njaudavid5@gmail.com',
  autoSendOnVerification: true,
  includeReceiptPdfLink: true,
  includeTruthChainProof: true,
  notifyOnDispatches: true,
};

const emailLogs: EmailSummaryLog[] = [
  {
    id: 'EML-1001',
    transactionId: 'TX-MSQ-882190',
    itemTitle: 'Apple iPhone 15 Pro Max 256GB - Natural Titanium',
    recipientEmail: 'njaudavid5@gmail.com',
    subject: 'ActionReceipt Verified Purchase Summary: iPhone 15 Pro Max (£650.00)',
    sentAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    status: 'DELIVERED',
    amount: 650.00,
    currency: 'GBP',
    truthChainProofHash: '0x8f3c...92a1',
    summaryHtml: `<div style="font-family: sans-serif; max-width: 600px; padding: 24px; background: #0f172a; color: #f8fafc; border-radius: 16px;">
      <h2 style="color: #34d399; margin-top: 0;">✓ ActionReceipt Remote Purchase Verified</h2>
      <p>Your remote purchase has successfully passed TruthChain multi-point identity, GPS LocationProof, and payout ownership checks.</p>
      <div style="background: #1e293b; padding: 16px; border-radius: 12px; margin: 16px 0;">
        <p style="margin: 4px 0;"><strong>Item:</strong> Apple iPhone 15 Pro Max 256GB</p>
        <p style="margin: 4px 0;"><strong>Amount:</strong> £650.00 GBP</p>
        <p style="margin: 4px 0;"><strong>Seller:</strong> Sarah Jenkins (Sole Trader)</p>
        <p style="margin: 4px 0;"><strong>TruthChain Status:</strong> 100% Consistent (0 Contradictions)</p>
      </div>
      <p style="font-size: 12px; color: #94a3b8;">Automated verification dispatch generated by ActionReceipt Engine.</p>
    </div>`
  }
];

export const notificationService = {
  getSettings(): NotificationSettings {
    return { ...notificationSettings };
  },

  updateSettings(newSettings: Partial<NotificationSettings>): NotificationSettings {
    notificationSettings = { ...notificationSettings, ...newSettings };
    return { ...notificationSettings };
  },

  getLogs(): EmailSummaryLog[] {
    return [...emailLogs];
  },

  sendAutomatedEmailSummary(tx: Transaction, recipientEmailOverride?: string): EmailSummaryLog {
    const recipient = recipientEmailOverride || notificationSettings.emailRecipient || 'njaudavid5@gmail.com';
    const proofHash = `0x${Math.floor(Math.random() * 1e12).toString(16)}`;
    const sentAt = new Date().toISOString();

    const summaryHtml = `
      <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #020617; color: #f8fafc; border-radius: 20px; overflow: hidden; border: 1px solid #1e293b; box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5);">
        <!-- Top Header -->
        <div style="background: linear-gradient(135deg, #059669 0%, #022c22 100%); padding: 28px 24px; text-align: center;">
          <div style="display: inline-block; background-color: rgba(255, 255, 255, 0.2); color: #ffffff; font-size: 11px; font-weight: bold; letter-spacing: 1px; padding: 4px 12px; border-radius: 20px; text-transform: uppercase; margin-bottom: 12px;">
            ACTIONRECEIPT AUTOMATED SUMMARY
          </div>
          <h1 style="color: #ffffff; font-size: 24px; margin: 0; font-weight: 800; tracking-tight: -0.025em;">
            ✓ Purchase Verification Complete
          </h1>
          <p style="color: #a7f3d0; font-size: 13px; margin-top: 6px; margin-bottom: 0;">
            Remote Purchase Verification Successful
          </p>
        </div>

        <!-- Body Content -->
        <div style="padding: 28px 24px;">
          <p style="font-size: 14px; color: #cbd5e1; line-height: 1.6; margin-top: 0;">
            Hello, your remote purchase verification for <strong>${tx.itemTitle}</strong> has passed all 7 safety checkpoints on <strong>TruthChain</strong>.
          </p>

          <!-- Transaction Card -->
          <div style="background-color: #0f172a; border: 1px solid #1e293b; border-radius: 14px; padding: 20px; margin: 20px 0;">
            <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
              <tr>
                <td style="color: #94a3b8; padding-bottom: 8px;">Transaction Ref:</td>
                <td style="color: #34d399; font-family: monospace; font-weight: bold; text-align: right; padding-bottom: 8px;">${tx.id}</td>
              </tr>
              <tr>
                <td style="color: #94a3b8; padding-bottom: 8px;">Item Title:</td>
                <td style="color: #ffffff; font-weight: bold; text-align: right; padding-bottom: 8px;">${tx.itemTitle}</td>
              </tr>
              <tr>
                <td style="color: #94a3b8; padding-bottom: 8px;">Price / Total:</td>
                <td style="color: #34d399; font-size: 16px; font-weight: bold; text-align: right; padding-bottom: 8px;">£${tx.itemPrice.toFixed(2)} GBP</td>
              </tr>
              <tr>
                <td style="color: #94a3b8; padding-bottom: 8px;">Seller Name:</td>
                <td style="color: #ffffff; text-align: right; padding-bottom: 8px;">${tx.seller?.fullName || 'Verified Seller'}</td>
              </tr>
              <tr>
                <td style="color: #94a3b8; padding-bottom: 8px;">TruthChain Status:</td>
                <td style="color: #10b981; font-weight: bold; text-align: right; padding-bottom: 8px;">100% RECONCILED ✓</td>
              </tr>
              <tr>
                <td style="color: #94a3b8;">Proof Hash:</td>
                <td style="color: #64748b; font-family: monospace; font-size: 11px; text-align: right;">${proofHash}</td>
              </tr>
            </table>
          </div>

          <!-- Bullet Points -->
          <ul style="color: #94a3b8; font-size: 12px; line-height: 1.8; padding-left: 20px; margin-bottom: 24px;">
            <li><strong style="color: #e2e8f0;">Seller Identity:</strong> Verified against official government registers & address check.</li>
            <li><strong style="color: #e2e8f0;">Payout Ownership:</strong> Verified payout account matched 100% to seller identity.</li>
            <li><strong style="color: #e2e8f0;">LiveCheck Proof:</strong> One-time token gesture and live condition verified.</li>
            <li><strong style="color: #e2e8f0;">LocationProof:</strong> GPS location anchored and verified.</li>
          </ul>

          <div style="text-align: center; margin-top: 28px; padding-top: 20px; border-top: 1px solid #1e293b;">
            <a href="https://ais-pre-357yfdgbskgo4gpnt5k6wm-318404455378.europe-west2.run.app/pay/${tx.id}" style="background-color: #10b981; color: #020617; font-weight: bold; font-size: 13px; text-decoration: none; padding: 12px 28px; border-radius: 10px; display: inline-block;">
              View Live Receipt & Delivery Details →
            </a>
          </div>
        </div>

        <!-- Footer -->
        <div style="background-color: #0f172a; padding: 16px 24px; text-align: center; border-top: 1px solid #1e293b;">
          <p style="color: #64748b; font-size: 11px; margin: 0;">
            ActionReceipt Automated Verification Infrastructure • Sent to ${recipient}
          </p>
        </div>
      </div>
    `;

    const log: EmailSummaryLog = {
      id: `EML-${Math.floor(1000 + Math.random() * 9000)}`,
      transactionId: tx.id,
      itemTitle: tx.itemTitle,
      recipientEmail: recipient,
      subject: `ActionReceipt Automated Verification Summary: ${tx.itemTitle} (£${tx.itemPrice.toFixed(2)})`,
      sentAt,
      status: 'DELIVERED',
      amount: tx.itemPrice,
      currency: 'GBP',
      truthChainProofHash: proofHash,
      summaryHtml
    };

    emailLogs.unshift(log);
    return log;
  }
};
